#!/bin/bash

#curl -X POST -d 'id=1&Submit=Submit' "http://192.168.1.48/dvwa/vulnerabilities/sqli/"
curl -v "http://192.168.1.48/dvwa/vulnerabilities/sqli/?id%3D1%26Submit%3DSubmit"
#wget "http://192.168.1.48/dvwa/vulnerabilities/sqli/?id%3D1%26Submit%3DSubmit%23"
